fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/woodruffw/zizmor
    rev: v0.7.0 
    hooks:
    - id: zizmor
      files: ^.github/workflows/.*\.yml$