[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2","numpy","Cython"]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "-s"

[tool.setuptools_scm]

