name: Continuous Integration
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        fortran-compiler:  [gfortran-9, gfortran-10]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    env:
      FC: ${{ matrix.fortran-compiler }}
      FCFLAGS: 
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Update system packages
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    ############################################################################
    #
    # Compilers....
    #
    # Gfortran 10 not available in Github CI stack, so install
    #
    - name: gfortran-10 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-10')
      run: |
        sudo apt-get install gfortran-10 gcc-10
        echo "CC=gcc-10" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

