name: Continuous Integration
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fortran-compiler:  [gfortran-8, gfortran-9, gfortran-10, gfortran-11, gfortran-12]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    env:
      FC: ${{ matrix.fortran-compiler }}
      CC: gcc

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: gfortran-8 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-8')
      run: |
        sudo apt-get install gfortran-10

    - name: gfortran-9 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-9')
      run: |
        sudo apt-get install gfortran-10

    - name: gfortran-10 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-10')
      run: |
        sudo apt-get install gfortran-10

    - name: gfortran-11 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-11')
      run: |
        sudo apt-get install gfortran-11

    - name: gfortran-12 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-12')
      run: |
        sudo apt-get install gfortran-12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        pip install -r requirements.txt

    - name: Test with tox
      run: tox -e py

