name: Coveralls
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fortran-compiler:  [gfortran-12]
        python-version: ['3.11']
    env:
      FC: ${{ matrix.fortran-compiler }}
      CC: gcc

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: gfortran-12 setup compiler
      if: contains(matrix.fortran-compiler, 'gfortran-12')
      run: |
        sudo apt-get install gfortran-12

    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-v1-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_dev.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest coveralls
        pip install -r requirements.txt

    - name: Run coveralls
      run: |
        coverage run --source=gfort2py -m pytest tests/
        coveralls

