
name: Test on Cygwin 
on: [push, pull_request]

jobs:
  CI:
    runs-on: windows-latest
    steps:
        - run: git config --global core.autocrlf input

        - uses: actions/checkout@v2

        - name: Install Cygwin
          uses: cygwin/cygwin-install-action@v4
          with:
            platform: x86_64
            install-dir: 'C:\tools\cygwin'
            packages: >-
                python39-devel python39-pip python-pip-wheel python-setuptools-wheel
                gcc-fortran git dash

        - name: Set Windows PATH
          uses: egor-tensin/cleanup-path@v3
          with:
            dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
        - name: Verify that bash is Cygwin bash
          run: |
            command bash
            bash -c "uname -svrmo"
        - name: Tell Cygwin's git about this repository.
          run: |
            dash -c "which git; /usr/bin/git config --system --add safe.directory /cygdrive/d/a/gfort2py/gfort2py"
        - name: Verify python version
          # Make sure it's the Cygwin one, not a Windows one
          run: |
            dash -c "which python3.9; /usr/bin/python3.9 --version -V"    
        - name: Install dependencies
          run: |
            dash -c "/usr/bin/python3.9 -m pip install --upgrade pip"
            dash -c "/usr/bin/python3.9 -m pip install build wheel pytest"
        - name: Install 
          run: |
            dash -c "/usr/bin/python3.9 -m pip install ."
        - name: Run tests
          run: |
              dash -c "/usr/bin/python3.9 -m pytest -v"

