name:  PyPy
on: [push, pull_request]

jobs:
  pypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 12}

    steps:
      - uses: actions/checkout@v4
      - name: Set up PyPy
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9' 
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel pytest

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build and test
        run:
          pypy3 -m build .
          pypy3 -m pytest -v
